# Generated by Django 6.0.3 on 2026-03-08 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_study_time', models.FloatField(default=0, help_text='Total minutes studied')),
                ('total_questions', models.IntegerField(default=0)),
                ('total_lectures', models.IntegerField(default=0, help_text='Total lecture minutes')),
            ],
            options={
                'verbose_name_plural': 'Daily Stats',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='StudySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, help_text='Date of the study session')),
                ('subject', models.CharField(choices=[('DSA', 'Data Structures & Algorithms'), ('OS', 'Operating Systems'), ('COA', 'Computer Organization & Architecture'), ('DBMS', 'Database Management Systems'), ('DL', 'Digital Logic'), ('MATHS', 'Engineering Mathematics'), ('CN', 'Computer Networks'), ('TOC', 'Theory of Computation'), ('CD', 'Compiler Design'), ('SE', 'Software Engineering'), ('APT', 'Aptitude')], max_length=10)),
                ('study_type', models.CharField(choices=[('Theory', 'Theory'), ('Practice', 'Practice'), ('Lecture', 'Lecture'), ('Revision', 'Revision')], max_length=10)),
                ('duration_minutes', models.FloatField(default=0, help_text='Duration in minutes (decimal)')),
                ('questions_solved', models.IntegerField(default=0)),
                ('lecture_minutes', models.IntegerField(default=0)),
                ('notes_created', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
